import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import aiCareerIllustration from './assets/ai-career.svg';
import roadmapIllustration from './assets/roadmap-ai.svg';

const API=import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api';
const careers=['AI/ML Engineer','Data Scientist','Full Stack Developer','Backend Developer','Frontend Developer','Data Analyst','DevOps Engineer','Cloud Engineer','Cybersecurity Analyst','Mobile App Developer','Product Analyst','QA Automation Engineer'];

async function api(path,opts={}){
  const token=localStorage.getItem('token');

  const res=await fetch(`${API}${path}`,{
    credentials:'include',
    ...opts,
    headers:{
      ...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),
      ...(token?{Authorization:`Bearer ${token}`}:{ }),
      ...(opts.headers||{})
    }
  });

  const data=await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(data.detail||data.message||'Something went wrong');
  return data;
}

const err=e=>e?.message||'Something went wrong. Please try again.';
function Auth({onLogin}){
 const [mode,setMode]=useState(new URLSearchParams(location.search).has('reset')?'reset':'login'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [token,setToken]=useState(new URLSearchParams(location.search).get('reset')||''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setMessage('');setLoading(true);try{
  if(mode==='register'){await api('/auth/register',{method:'POST',body:JSON.stringify({name,email,password})});setMessage('Account created. You can sign in now.');setMode('login');}
  else if(mode==='forgot'){const d=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});setMessage(d.development_reset_token?`Development reset token: ${d.development_reset_token}`:d.message);}
  else if(mode==='reset'){await api('/auth/reset-password',{method:'POST',body:JSON.stringify({token,password})});setMessage('Password reset successfully. Sign in with your new password.');setMode('login');setPassword('');}
  else {const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});if(d.token)localStorage.setItem('token',d.token);onLogin(d.user)}
 }catch(e){setMessage(err(e))}finally{setLoading(false)}};
 return <div className="auth-page"><div className="auth-art"><img src={aiCareerIllustration}/><div><span className="eyebrow">AI CAREER & PLACEMENT COPILOT</span><h1>Your career, intelligently planned.</h1><p>Resume intelligence, personalized learning, interview coaching and job discovery in one professional workspace.</p></div></div><div className="auth-card"><div className="brand"><span>✦</span> CareerCopilot</div><h2>{mode==='login'?'Welcome back':mode==='register'?'Create your account':mode==='forgot'?'Recover your account':'Set a new password'}</h2><p className="muted">{mode==='reset'?'Choose a strong new password.':mode==='forgot'?'We will prepare a secure reset link for your account.':'Build a career plan that is actually tailored to you.'}</p><form onSubmit={submit}>
 {mode==='register'&&<Field label="Full name" value={name} onChange={setName} required/>}{mode!=='reset'&&<Field label="Email" type="email" value={email} onChange={setEmail} required/>}{(mode==='login'||mode==='register'||mode==='reset')&&<Field label="Password" type="password" value={password} onChange={setPassword} required minLength={8}/>} {mode==='reset'&&<Field label="Reset token" value={token} onChange={setToken} required/>}
 {message&&<div className="notice">{message}</div>}<button className="primary full" disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':mode==='forgot'?'Send reset instructions':'Reset password'}</button>
 </form><div className="auth-links">{mode==='login'&&<><button className="text-btn" onClick={()=>setMode('forgot')}>Forgot password?</button><button className="text-btn" onClick={()=>setMode('register')}>Create an account</button></>}{mode==='register'&&<button className="text-btn" onClick={()=>setMode('login')}>Already have an account? Sign in</button>}{mode==='forgot'&&<button className="text-btn" onClick={()=>setMode('login')}>Back to sign in</button>}{mode==='reset'&&<button className="text-btn" onClick={()=>setMode('login')}>Back to sign in</button>}</div></div></div>
}
function Field({label,value,onChange,type='text',...props}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>}

function App({user,onLogout}){
 const [tab,setTab]=useState('dashboard'); const [profile,setProfile]=useState(null); const [resume,setResume]=useState(null); const [careersData,setCareersData]=useState([]); const [selectedCareer,setSelectedCareer]=useState(''); const [roadmap,setRoadmap]=useState([]); const [skillIntel,setSkillIntel]=useState(null); const [jobs,setJobs]=useState([]); const [dashboard,setDashboard]=useState(null); const [interview,setInterview]=useState(null); const [answers,setAnswers]=useState({}); const [evaluations,setEvaluations]=useState({}); const [analytics,setAnalytics]=useState(null); const [goals,setGoals]=useState([]); const [practice,setPractice]=useState([]); const [practiceCat,setPracticeCat]=useState('technical'); const [portfolio,setPortfolio]=useState([]); const [coach,setCoach]=useState(''); const [question,setQuestion]=useState(''); const [explanation,setExplanation]=useState(''); const [loading,setLoading]=useState(false); const [toast,setToast]=useState('');
 const skills=profile?.skills||[];
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),3500)};
 const refresh=async()=>{try{const [p,d,g,po,a]=await Promise.all([api('/profile'),api('/product/dashboard'),api('/product/goals'),api('/product/portfolio'),api('/interview/analytics')]);setProfile(p.profile);setDashboard(d);setGoals(g.goals);setPortfolio(po.projects);setAnalytics(a);if(p.profile?.target_role)setSelectedCareer(p.profile.target_role)}catch(e){notify(err(e))}};
 useEffect(()=>{refresh()},[]);
 const chooseCareer=async c=>{setSelectedCareer(c);setLoading(true);try{const [r,s]=await Promise.all([api('/career/roadmap',{method:'POST',body:JSON.stringify({skills,target:c})}),api('/career/skills',{method:'POST',body:JSON.stringify({skills,target:c})})]);setRoadmap(r.roadmap);setSkillIntel(s);await saveProfile({...profile,target_role:c});setTab('roadmap')}catch(e){notify(err(e))}finally{setLoading(false)}};
 const saveProfile=async data=>{const d=await api('/profile',{method:'PUT',body:JSON.stringify({...data,skills:data.skills||skills})});setProfile(d.profile);return d.profile};
 const analyze=async file=>{if(!file)return;setLoading(true);try{const fd=new FormData();fd.append('file',file);const d=await api('/resume/analyze',{method:'POST',body:fd});setResume(d);await saveProfile({...profile,skills:d.skills});notify('Resume analyzed and profile skills updated.')}catch(e){notify(err(e))}finally{setLoading(false)}};
 const loadCareers=async()=>{setLoading(true);try{const d=await api('/career/recommend',{method:'POST',body:JSON.stringify({skills})});setCareersData(d.recommendations)}catch(e){notify(err(e))}finally{setLoading(false)}};
 const loadJobs=async()=>{if(!selectedCareer)return notify('Select a target career first.');setLoading(true);try{const d=await api(`/jobs/match?career=${encodeURIComponent(selectedCareer)}`);setJobs(d.matches)}catch(e){notify(err(e))}finally{setLoading(false)}};
 const startInterview=async(type='mock')=>{if(!selectedCareer)return notify('Select a target career first.');setLoading(true);try{const d=await api('/interview/start',{method:'POST',body:JSON.stringify({target:selectedCareer,session_type:type,difficulty:'adaptive',skills})});setInterview(d);setAnswers({});setEvaluations({});setTab('interview')}catch(e){notify(err(e))}finally{setLoading(false)}};
 const submitAnswer=async q=>{setLoading(true);try{const d=await api('/interview/answer',{method:'POST',body:JSON.stringify({session_id:interview.session_id,question_id:q.id,answer:answers[q.id]||''})});setEvaluations(v=>({...v,[q.id]:d.evaluation}));notify('AI evaluation ready.')}catch(e){notify(err(e))}finally{setLoading(false)}};
 const finishInterview=async()=>{try{const d=await api(`/interview/finish/${interview.session_id}`,{method:'POST'});notify(`Interview completed — score ${d.score}/100`);await refresh()}catch(e){notify(err(e))}};
 const loadCoach=async()=>{setLoading(true);try{const d=await api('/career/coach',{method:'POST',body:JSON.stringify({target:selectedCareer,skills})});setCoach(d.advice)}catch(e){notify(err(e))}finally{setLoading(false)}};
 const loadSkill=async()=>{if(!selectedCareer)return;try{const d=await api('/career/skills',{method:'POST',body:JSON.stringify({skills,target:selectedCareer})});setSkillIntel(d)}catch(e){notify(err(e))}};
 const loadRoadmap=async()=>{if(!selectedCareer)return notify('Select a target career first.');try{const d=await api('/career/roadmap',{method:'POST',body:JSON.stringify({skills,target:selectedCareer})});setRoadmap(d.roadmap);await loadSkill()}catch(e){notify(err(e))}};
 const addGoal=async()=>{const title=prompt('Goal title');if(!title)return;await api('/product/goals',{method:'POST',body:JSON.stringify({title,category:'roadmap'})});refresh()};
 const toggleGoal=async g=>{await api(`/product/goals/${g.id}`,{method:'PATCH',body:JSON.stringify({completed:!g.completed})});refresh()};
 const loadPractice=async c=>{setPracticeCat(c);try{const d=await api(`/product/practice?category=${c}`);setPractice(d.questions)}catch(e){notify(err(e))}};
 const [practiceAnswers,setPracticeAnswers]=useState({}); const [practiceResults,setPracticeResults]=useState({});
 const submitPractice=async q=>{try{const d=await api('/product/practice/submit',{method:'POST',body:JSON.stringify({category:practiceCat,question:q.question,answer:practiceAnswers[q.id]||''})});setPracticeResults(v=>({...v,[q.id]:d.evaluation}))}catch(e){notify(err(e))}};
 const [edit,setEdit]=useState(false); const [editForm,setEditForm]=useState({});
 useEffect(()=>{if(profile)setEditForm(profile)},[profile]);
 const nav=[['dashboard','Overview','⌂'],['profile','My Profile','◉'],['resume','Resume Studio','▣'],['careers','Career Discovery','✦'],['skills','Skill Intelligence','◆'],['roadmap','Roadmap','➜'],['coach','AI Coach','◈'],['interview','Interview','◌'],['jobs','Job Matching','▤'],['learning','Learning Hub','◫'],['practice','Practice Zone','◇'],['portfolio','Portfolio','◍'],['goals','Goals','✓']];
 return <div className="app"><aside><div className="brand"><span>✦</span> CareerCopilot</div><div className="side-user"><div className="avatar">{profile?.profile_photo?<img src={profile.profile_photo} alt="Profile"/>:(user.name||'U').slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><small>{selectedCareer||'Choose your target career'}</small></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}</nav><button className="logout" onClick={async()=>{try{await api('/auth/logout',{method:'POST'});}finally{localStorage.removeItem('token');onLogout()}}}>Sign out</button></aside><main><header className="topbar"><div><span className="eyebrow">AI-POWERED CAREER PLATFORM</span><h1>{nav.find(x=>x[0]===tab)?.[1]||'Overview'}</h1></div><div className="top-actions"><span className="career-pill">{selectedCareer||'No target selected'}</span><button className="icon-btn" onClick={refresh}>↻</button></div></header>
 {tab==='dashboard'&&<Dashboard dashboard={dashboard} profile={profile} setTab={setTab} selectedCareer={selectedCareer} />}
 {tab==='profile'&&<Profile profile={profile} edit={edit} setEdit={setEdit} form={editForm} setForm={setEditForm} save={async()=>{await saveProfile(editForm);setEdit(false);notify('Profile updated')}} />}
 {tab==='resume'&&<ResumeStudio analyze={analyze} resume={resume} loading={loading}/>} 
 {tab==='careers'&&<CareerDiscovery data={careersData} load={loadCareers} choose={chooseCareer} selected={selectedCareer} loading={loading}/>} 
 {tab==='skills'&&<Skills intel={skillIntel} load={loadSkill} career={selectedCareer} />} 
 {tab==='roadmap'&&<Roadmap roadmap={roadmap} load={loadRoadmap} career={selectedCareer} loading={loading}/>} 
 {tab==='coach'&&<Coach coach={coach} load={loadCoach} career={selectedCareer} loading={loading}/>} 
 {tab==='interview'&&<Interview interview={interview} start={startInterview} answers={answers} setAnswers={setAnswers} evals={evaluations} submit={submitAnswer} finish={finishInterview} analytics={analytics} career={selectedCareer} loading={loading}/>} 
 {tab==='jobs'&&<Jobs jobs={jobs} load={loadJobs} career={selectedCareer} />} 
 {tab==='learning'&&<Learning intel={skillIntel} career={selectedCareer}/>} 
 {tab==='practice'&&<Practice practice={practice} load={loadPractice} cat={practiceCat} answers={practiceAnswers} setAnswers={setPracticeAnswers} results={practiceResults} submit={submitPractice}/>} 
 {tab==='portfolio'&&<Portfolio projects={portfolio} career={selectedCareer} reload={refresh}/>} 
 {tab==='goals'&&<Goals goals={goals} add={addGoal} toggle={toggleGoal}/>} 
 </main>{toast&&<div className="toast">{toast}</div>}{loading&&<div className="global-loader">Working…</div>}</div>
}

function Dashboard({dashboard,profile,setTab,selectedCareer}){if(!dashboard)return <Empty title="Preparing your workspace…"/>;return <><section className="hero-grid"><div className="hero-copy"><span className="eyebrow">YOUR PERSONAL CAREER COMMAND CENTER</span><h2>Build skills. Practice smarter. <em>Get placement-ready.</em></h2><p>Your workspace connects resume intelligence, career planning, interview coaching and relevant opportunities.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab('careers')}>{selectedCareer?'Review career fit':'Discover your career'} →</button><button className="secondary" onClick={()=>setTab('resume')}>Analyze resume</button></div></div><img className="hero-art" src={aiCareerIllustration}/></section><div className="stat-grid"><Stat label="Career readiness" value={`${dashboard.readiness_score}%`} sub="Explainable score"/><Stat label="Skill coverage" value={`${dashboard.roadmap_coverage}%`} sub={selectedCareer||'Choose a target'}/><Stat label="Interview average" value={`${dashboard.interview_average}%`} sub="Across completed sessions"/><Stat label="Profile" value={`${Math.round(dashboard.profile_complete)}%`} sub="Completeness"/></div><div className="two-col"><Panel title="Your next move"><div className="next-list"><div><b>{selectedCareer?'Close your top skill gap':'Choose a target career'}</b><span>{selectedCareer?'Open Skill Intelligence and start with the highest-priority gap.':'Career Discovery will compare your skills against multiple paths.'}</span></div><div><b>Practice with intent</b><span>Use Mock Interview or Practice Zone and review your feedback.</span></div><div><b>Build proof</b><span>Create a role-aligned portfolio project and publish a case study.</span></div></div></Panel><Panel title="Readiness breakdown"><div className="breakdown">{Object.entries(dashboard.readiness_breakdown||{}).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><div className="bar"><i style={{width:`${v}%`}}/></div><b>{v}%</b></div>)}</div></Panel></div></>}
function Stat({label,value,sub}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Panel({title,children,action}){return <section className="panel"><div className="panel-head"><h3>{title}</h3>{action}</div>{children}</section>}
function Profile({profile,edit,setEdit,form,setForm,save}){
 const photo=e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){alert('Please choose an image file.');return}if(file.size>2*1024*1024){alert('Please choose an image smaller than 2 MB.');return}const reader=new FileReader();reader.onload=()=>setForm({...form,profile_photo:reader.result});reader.readAsDataURL(file)};
 const editing=edit||!profile;
 const avatar=form.profile_photo||profile?.profile_photo;
 return <section className="profile-layout"><Panel title="My Profile" action={profile&&<button className="secondary" onClick={()=>setEdit(!edit)}>{edit?'Cancel':'Edit profile'}</button>}>
 <div className="profile-top"><div className="profile-avatar">{avatar?<img src={avatar} alt="Profile"/>:(profile?.name||'U').slice(0,1).toUpperCase()}</div><div><h2>{profile?.name||'Complete your profile'}</h2><p>{profile?.target_role||'Choose your target career'}</p><span className="muted">{profile?.location||'Location not added'} · {profile?.experience_level||'Student'}</span></div></div>
 {editing?<div className="form-grid"><label className="field photo-field"><span>Profile photo</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={photo}/><small>PNG, JPG or WEBP · max 2 MB</small></label>{['name','education','branch','location','experience_level','target_role','interests','bio'].map(k=><Field key={k} label={k.replaceAll('_',' ')} value={form[k]||''} onChange={v=>setForm({...form,[k]:v})} required={k==='name'}/>)}<label className="field"><span>Skills (comma separated)</span><input value={(form.skills||[]).join(', ')} onChange={e=>setForm({...form,skills:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><button className="primary" onClick={save}>Save changes</button></div>:<div className="detail-grid"><Detail k="Education" v={profile.education}/><Detail k="Branch" v={profile.branch}/><Detail k="Interests" v={profile.interests}/><Detail k="Experience" v={profile.experience_level}/><Detail k="Skills" v={profile.skills?.join(', ')}/><Detail k="About" v={profile.bio}/></div>}</Panel></section>}
function Detail({k,v}){return <div className="detail"><span>{k}</span><b>{v||'Not added yet'}</b></div>}
function ResumeStudio({analyze,resume,loading}){return <div className="two-col"><Panel title="AI Resume Studio"><p className="muted">Upload your latest resume. The system extracts skills, estimates role fit and runs practical ATS-style checks.</p><label className="upload"><input type="file" accept=".pdf,.docx,.txt" onChange={e=>analyze(e.target.files?.[0])}/><span>📄 Choose PDF, DOCX or TXT</span></label>{loading&&<Loading/>}{resume&&<div className="result-grid"><Stat label="Resume score" value={`${resume.score}%`} sub="Overall signal"/><Stat label="Skills detected" value={resume.skills?.length||0} sub="Extracted from resume"/><Stat label="ATS keyword coverage" value={`${resume.ats?.keyword_coverage||0}%`} sub="Targeting baseline"/></div>}</Panel>{resume&&<Panel title="Role fit & improvements"><h4>Detected strengths</h4><Tags items={resume.strengths}/><h4>Recommended improvements</h4><ul className="clean-list">{resume.suggestions?.map(x=><li key={x}>{x}</li>)}</ul><h4>Career matches</h4>{resume.career_matches?.map(x=><div className="mini-row" key={x.career}><b>{x.career}</b><span>{x.match}% fit</span></div>)}</Panel>}</div>}
function CareerDiscovery({data,load,choose,selected,loading}){return <><section className="hero-strip"><div><span className="eyebrow">CAREER DISCOVERY</span><h2>Compare paths using your actual skills.</h2><p>Choose a target once; the roadmap, interviews, coach and jobs all follow it.</p></div><button className="primary" onClick={load}>{loading?'Analyzing…':'Analyze my career fit'}</button></section><div className="career-grid">{data.map(c=><div className={`career-card ${selected===c.career?'selected':''}`} key={c.career}><div className="career-title"><div><span className="eyebrow">{c.match}% FIT</span><h3>{c.career}</h3></div><span className="score">{c.match}%</span></div><p>Core skills: {c.required.join(', ')}</p><Tags items={c.missing?.slice(0,4)} danger/><button className="secondary" onClick={()=>choose(c.career)}>Choose this career</button></div>)}</div>{!data.length&&<Empty title="Run career discovery" text="Your skills will be compared against multiple career paths."/>}</>}
function Skills({intel,load,career}){return <Panel title="Personal Skill Intelligence"><div className="panel-head"><div><p className="muted">{career?'Gap analysis for '+career:'Select a target career first.'}</p></div><button className="secondary" onClick={load}>Refresh analysis</button></div>{intel?<><div className="coverage"><strong>{intel.coverage}%</strong><span>core skill coverage</span></div><div className="skill-columns"><div><h4>Current skills</h4><Tags items={intel.current_skills}/></div><div><h4>Priority gaps</h4>{intel.priority_gaps?.map(x=><div className="gap" key={x.skill}><b>{x.skill}</b><span className={x.priority==='High'?'high':''}>{x.priority}</span><small>{x.reason}</small></div>)}</div></div></>:<Empty title="No skill intelligence yet" text="Choose a career from Career Discovery."/>}</Panel>}
function Roadmap({roadmap,load,career,loading}){return <div className="two-col"><Panel title="Adaptive Roadmap"><div className="roadmap-head"><div><span className="eyebrow">PERSONALIZED FOR</span><h2>{career||'No target career'}</h2><p className="muted">Each milestone connects learning, practice and portfolio evidence.</p></div><img src={roadmapIllustration}/></div><button className="primary" onClick={load}>{loading?'Building…':'Regenerate roadmap'}</button>{roadmap.map(x=><div className="road-step" key={x.week}><div className="step-no">{x.week}</div><div><span className="eyebrow">WEEK {x.week}</span><h3>{x.title}</h3><p><b>Focus:</b> {x.focus}</p><ul>{x.tasks.map(t=><li key={t}>{t}</li>)}</ul>{x.resources?.length>0&&<div className="resource-row">{x.resources.map(r=><a key={r.name} href={r.url} target="_blank" rel="noreferrer">Learn {r.name} ↗</a>)}</div>}</div></div>)}</Panel><Panel title="Roadmap philosophy"><p>Progress is based on what you already know. Missing core skills are prioritized, while project and placement milestones turn learning into evidence.</p><div className="callout">💡 <b>Tip:</b> Add one measurable outcome to every project you complete.</div></Panel></div>}
function Coach({coach,load,career,loading}){return <Panel title="AI Career Coach"><div className="coach-hero"><img src={aiCareerIllustration}/><div><span className="eyebrow">CONTEXT-AWARE GUIDANCE</span><h2>{career||'Choose a target career'}</h2><p>Advice is grounded in your profile and current skill set.</p><button className="primary" onClick={load}>{loading?'Thinking…':'Get my next actions'}</button></div></div>{coach&&<div className="ai-response">{coach}</div>}</Panel>}
function Interview({interview,start,answers,setAnswers,evals,submit,finish,analytics,career,loading}){return <div className="two-col"><Panel title="AI Mock Interview"><p className="muted">Practice like a real interview. Questions are role-specific and your answers are evaluated with actionable feedback.</p><div className="hero-actions"><button className="primary" onClick={()=>start('mock')}>Start mock interview</button><button className="secondary" onClick={()=>start('practice')}>Practice interview</button></div>{interview?.questions?.map(q=><div className="question-card" key={q.id}><div className="question-meta"><span>{q.category}</span><span>{q.difficulty}</span></div><h3>{q.question}</h3><textarea placeholder="Answer as you would in an interview…" value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/><button className="secondary" onClick={()=>submit(q)}>Evaluate answer</button>{evals[q.id]&&<div className="evaluation"><strong>{evals[q.id].score}/100</strong><p>{evals[q.id].feedback}</p><b>Missing points</b><ul>{(evals[q.id].missing_points||[]).map(x=><li key={x}>{x}</li>)}</ul><b>Ideal direction</b><p>{evals[q.id].ideal_answer}</p></div>}</div>)}{interview&&<button className="primary" onClick={finish}>Finish interview</button>}</Panel><Panel title="Interview analytics"><div className="analytics-big">{analytics?.average_score||0}<small>average score</small></div><div className="mini-grid">{Object.entries(analytics?.by_category||{}).map(([k,v])=><Stat key={k} label={k} value={`${v}%`} sub="Average"/>)}</div><p className="muted">Completed attempts: {analytics?.attempts||0}. Review your feedback after every session and repeat weak categories.</p></Panel></div>}
function Jobs({jobs,load,career}){return <Panel title="Job Matching"><div className="panel-head"><p className="muted">Relevant opportunities for {career||'your selected career'}.</p><button className="primary" onClick={load}>Find matching jobs</button></div>{jobs.map(j=><div className="job" key={j.id}><div><span className="eyebrow">{j.match_percentage}% MATCH</span><h3>{j.title}</h3><p>{j.company} · {j.location} · {j.experience_level}</p><p>{j.description}</p><Tags items={j.missing_skills} danger/></div><a className="apply" href={j.apply_url} target="_blank" rel="noreferrer">View application ↗</a></div>)}{!jobs.length&&<Empty title="Find relevant opportunities" text="Your target career and profile skills will be used for matching."/>}</Panel>}
function Learning({intel,career}){const items=intel?.priority_gaps||[];return <Panel title="Learning Hub"><p className="muted">Structured next-step resources for {career||'your career'}.</p>{items.length?items.map(x=><div className="learning-card" key={x.skill}><div><span className="eyebrow">{x.priority} PRIORITY</span><h3>{x.skill}</h3><p>{x.reason}</p></div><a href={x.resource} target="_blank" rel="noreferrer">Open resource ↗</a></div>):<Empty title="No priority gaps yet" text="Run Skill Intelligence after choosing a career."/>}</Panel>}
function Practice({practice,load,cat,answers,setAnswers,results,submit}){return <Panel title="Practice Zone"><div className="tabs">{['technical','coding','aptitude','hr'].map(x=><button className={cat===x?'active':''} key={x} onClick={()=>load(x)}>{x}</button>)}</div>{practice.map(q=><div className="question-card" key={q.id}><span className="eyebrow">{cat}</span><h3>{q.question}</h3><textarea value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} placeholder="Write your answer…"/><button className="secondary" onClick={()=>submit(q)}>Get AI feedback</button>{results[q.id]&&<div className="evaluation"><strong>{results[q.id].score}/100</strong><p>{results[q.id].feedback}</p></div>}</div>)}{!practice.length&&<Empty title="Choose a practice category" text="Practice technical, coding, aptitude and HR skills."/>}</Panel>}
function Portfolio({projects,career,reload}){const [title,setTitle]=useState('');const [description,setDescription]=useState('');const add=async()=>{if(!title)return;await api('/product/portfolio',{method:'POST',body:JSON.stringify({title,description,tech_stack:career||''})});setTitle('');setDescription('');reload()};return <div className="two-col"><Panel title="Portfolio & Project Guidance"><p className="muted">Build proof that maps directly to {career||'your target role'}.</p><Field label="Project title" value={title} onChange={setTitle}/><Field label="What will you build?" value={description} onChange={setDescription}/><button className="primary" onClick={add}>Add project</button></Panel><Panel title="My projects">{projects.map(p=><div className="project" key={p.id}><span className="eyebrow">{p.status}</span><h3>{p.title}</h3><p>{p.description}</p><small>{p.tech_stack}</small></div>)}{!projects.length&&<Empty title="No projects yet" text="Add a project and turn it into portfolio evidence."/>}</Panel></div>}
function Goals({goals,add,toggle}){return <Panel title="Goals & Milestones" action={<button className="primary" onClick={add}>+ Add goal</button>}><p className="muted">Keep roadmap milestones and preparation tasks visible.</p>{goals.map(g=><div className={`goal ${g.completed?'done':''}`} key={g.id}><button onClick={()=>toggle(g)}>{g.completed?'✓':'○'}</button><div><b>{g.title}</b><span>{g.description||'Personal career goal'}</span></div></div>)}{!goals.length&&<Empty title="Set your first goal" text="Examples: finish a project, complete a mock interview, or close a skill gap."/>}</Panel>}
function Tags({items=[],danger=false}){return <div className="tags">{items.map(x=><span className={danger?'danger':''} key={x}>{x}</span>)}</div>}
function Empty({title,text='Start by completing your profile.',action}){return <div className="empty"><div className="empty-icon">✦</div><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}>Get started</button>}</div>}
function Loading(){return <div className="loading"><span/> Preparing your analysis…</div>}

function Root(){const [user,setUser]=useState(null);const [checking,setChecking]=useState(true);useEffect(()=>{api('/auth/me').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setChecking(false))},[]);if(checking)return <div className="splash">✦<span>Loading CareerCopilot…</span></div>;return user?<App user={user} onLogout={()=>setUser(null)}/>:<Auth onLogin={setUser}/>}

createRoot(document.getElementById('root')).render(<Root/>);
